/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.clsVerPedidos;

/**
 *
 * @author Sena CSET
 */
public class frmVerPedidosAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmVerPedidosVend
     */
    public frmVerPedidosAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.creartabla();
        this.tablaVerPedidos();
    }
    clsVerPedidos objVp = new clsVerPedidos();
     frmDetalleAdmin objDet = new frmDetalleAdmin();
    NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
    DefaultTableModel tabladatos;
public String Numero;

    public void llamarRegresar() {
        frmInicioVendedor objIn = new frmInicioVendedor();
        objIn.setVisible(true);
        //dfd
        this.setVisible(false);
    }
   /* public void llamarDetalle(){
    frmDetalleAdmin objDet = new frmDetalleAdmin();
    objDet.setVisible(true);
    this.setVisible(false);
    }*/

    public void creartabla() {
        Object modelodata[][] = new Object[0][0];
        Object modelotitulos[] = {"Pedido", "Vendedor", "Cliente", "Cantidad", "Valor Total", "Estado", " Fecha"};
        tabladatos = new DefaultTableModel();
        tabladatos = new DefaultTableModel(modelodata, modelotitulos);

        this.tblPedidos.setModel(this.tabladatos);
    }

    public void borrartabla() {
        while (0 < this.tblPedidos.getRowCount()) {
            tblPedidos.setModel(new DefaultTableModel());
            this.creartabla();
        }
    }

    public void tablaVerPedidos() {
        String Pedido;
        
        try {
            this.borrartabla();
            objVp.VerPedidosVendedor();
            while (objVp.datos.next() == true) {
                Pedido = objVp.datos.getString(1);
                String Vendedor = objVp.datos.getString(3);
                String Cliente = objVp.datos.getString(4);
                String Cantidad = objVp.datos.getString(2);
                String Precio = format.format(objVp.datos.getInt(5));
                String Estado = objVp.datos.getString(6);
                String Fecha = objVp.datos.getString(7);

                Object fila[] = {Pedido, Vendedor, Cliente,Cantidad,Precio,Estado,Fecha};
                tabladatos.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se ha podido mostrar, lo siento" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDetalleAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 670));
        setSize(new java.awt.Dimension(1200, 670));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnDetalleAdmin.setBackground(new java.awt.Color(58, 155, 220));
        btnDetalleAdmin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDetalleAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalleAdmin.setText("Ver detalle");
        btnDetalleAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetalleAdmin);
        btnDetalleAdmin.setBounds(1040, 120, 105, 32);

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N pedido", "Vendedor", "Cliente", "Cantidad", "Valor Total", "Estado", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 1114, 360);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setText("Pedidos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 50, 100, 32);

        btnRegresar.setBackground(new java.awt.Color(255, 89, 89));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(1080, 20, 93, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.llamarRegresar();    // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
      int filaSeleccionada = tblPedidos.getSelectedRow();
        Numero = tblPedidos.getValueAt(filaSeleccionada, 0).toString();
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnDetalleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleAdminActionPerformed
   if (Numero != null) {
            // Llamar al método llamarDetalle() y pasar el número de pedido
           
            objDet.setNumeroPedido(tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 0).toString());
            objDet.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila para ver el detalle");
        }
       
    }//GEN-LAST:event_btnDetalleAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVerPedidosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVerPedidosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVerPedidosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVerPedidosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVerPedidosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleAdmin;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
